import { MethodInfo } from '../types';

// Definición de todos los métodos numéricos disponibles
export const methods: Record<string, MethodInfo> = {
  biseccion: {
    name: 'Bisección',
    description: 'Encuentra raíces mediante cambio de signo en un intervalo',
    parameters: {
      f: 'Función f(x)',
      a: 'Límite inferior',
      b: 'Límite superior',
      tolerance: 'Tolerancia',
      max_iterations: 'Máximo de iteraciones',
    },
    convergence: 'Lineal',
    pros: ['Siempre converge si hay cambio de signo', 'Simple de implementar'],
    cons: ['Convergencia lenta', 'Requiere intervalo con cambio de signo'],
    requirements: 'f(a) * f(b) < 0',
  },
  newton_raphson: {
    name: 'Newton-Raphson',
    description: 'Método cuadrático usando función y su derivada',
    parameters: {
      f: 'Función f(x)',
      f_prime: 'Derivada f\'(x)',
      x0: 'Valor inicial',
      tolerance: 'Tolerancia',
      max_iterations: 'Máximo de iteraciones',
    },
    convergence: 'Cuadrática',
    pros: ['Convergencia muy rápida', 'Precisión alta'],
    cons: ['Requiere derivada', 'Puede divergir', 'Sensible al punto inicial'],
    requirements: 'f\'(x) ≠ 0 en la raíz',
  },
  secante: {
    name: 'Secante',
    description: 'Aproximación de Newton-Raphson sin derivada analítica',
    parameters: {
      f: 'Función f(x)',
      x0: 'Valor inicial x₀',
      x1: 'Valor inicial x₁',
      tolerance: 'Tolerancia',
      max_iterations: 'Máximo de iteraciones',
    },
    convergence: 'Superlineal (~1.618)',
    pros: ['No requiere derivada', 'Más rápido que bisección'],
    cons: ['Menos preciso que Newton', 'Puede divergir'],
    requirements: 'Dos puntos iniciales diferentes',
  },
  punto_fijo: {
    name: 'Punto Fijo',
    description: 'Iteración funcional g(x) = x',
    parameters: {
      g: 'Función de iteración g(x)',
      x0: 'Valor inicial',
      tolerance: 'Tolerancia',
      max_iterations: 'Máximo de iteraciones',
    },
    convergence: 'Lineal',
    pros: ['Simple de implementar', 'Útil para ecuaciones no algebraicas'],
    cons: ['Convergencia lenta', 'Requiere |g\'(x)| < 1'],
    requirements: '|g\'(x)| < 1 para convergencia',
  },
  jacobi: {
    name: 'Jacobi',
    description: 'Método iterativo para sistemas lineales',
    parameters: {
      A: 'Matriz de coeficientes',
      vector_b: 'Vector de términos independientes',
      tolerance: 'Tolerancia',
      max_iterations: 'Máximo de iteraciones',
    },
    convergence: 'Lineal',
    pros: ['Simple de paralelizar', 'Memoria eficiente'],
    cons: ['Puede converger lentamente', 'No siempre converge'],
    requirements: 'Matriz diagonalmente dominante',
  },
  taylor: {
    name: 'Serie de Taylor',
    description: 'Expansión en series de potencias alrededor de un punto',
    parameters: {
      f: 'Función f(x)',
      x0: 'Punto de expansión',
      n_terms: 'Número de términos',
      eval_x: 'Punto de evaluación',
    },
    convergence: 'Analítica',
    pros: ['Alta precisión local', 'Base para otros métodos'],
    cons: ['Solo válido cerca del punto de expansión', 'Puede divergir lejos'],
    requirements: 'Función analítica en el punto',
  },
  maclaurin: {
    name: 'Serie de Maclaurin',
    description: 'Expansión en series de potencias alrededor de cero',
    parameters: {
      f: 'Función f(x)',
      n_terms: 'Número de términos',
      eval_x: 'Punto de evaluación',
    },
    convergence: 'Analítica',
    pros: ['Caso especial de Taylor', 'Simetría en cero'],
    cons: ['Limitado a expansiones en cero', 'Mismo que Taylor'],
    requirements: 'Función analítica en cero',
  },
};